name: CI/CD blank
on:
  push:
    branches: ["tst", "uat"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.ref_name }}
    steps:
      - name: echo env
        run: |
           echo ${{ github.ref_name ,,}}
           echo ${{ github.ref_name ^^}}
         
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
  api-tests: 
     if: github.ref == 'refs/heads/prod'
     runs-on: ubuntu-latest
     steps:
     - name: some prod echo
       run: echo "it's a prod"

  notapi-tests: 
     if: github.ref == 'refs/heads/tst'
     runs-on: ubuntu-latest
     steps:
     - name: some notprod echo
       run: echo "it's not a prod"
