#name: CICD backend-api
#on:
  #push:
    #branches:
      #- main
name: CICD BLANK
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: environment  
#env:
  #AWS_REGION: ${{ secrets.AWS_REGION }}  


  
permissions:
  contents: read

jobs:  
  deploy:
    runs-on: ubuntu-latest
    #environment:
      #name: tst
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Run database migration
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/${{ github.event.inputs.environment }}/mongo-atlas/protocol"
          env_variable_name: "DB_PROTOCOL"
      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/${{ github.event.inputs.environment }}/getstream-io/api-key"
          env_variable_name: "GETSTREAM_IO_API_KEY"
        env:
          PHOTOS_CDN_BASE: images.api.vybzapp.com
          AWS_S3_AVATAR_BUCKET_URL: https://${{ github.event.inputs.environment }}-vybz-public.s3.${{ env.AWS_REGION }}.amazonaws.com/new_avatars
          AWS_S3_PROMO_IMG_BUCKET_URL: https://${{ github.event.inputs.environment }}-vybz-public.s3.${{ env.AWS_REGION }}.amazonaws.com/promo/imgs
          AWS_S3_MEDIA_CONTENT_BUCKET_NAME: ${{ github.event.inputs.environment }}-vybz-bucket-media
      - name: Run
        run: |
          echo "dkdkdk"
          
     
      
     
 
